#!/bin/bash

flag=" "
if [ $# -ne 0 ] ; then
  flag=$1
fi

if [ -e ../lib/libwstore.a ] ; then \rm ../lib/libwstore.a ; fi
gfortran -c -Wall -Wno-surprising $flag -O3 -Iinc src/*.f
ar -r ../lib/libwstore.a *.o
\rm *.o
